/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_web_computing_HelloWorld_HelloWorldJNI */

#ifndef _Included_de_web_computing_HelloWorld_HelloWorldJNI
#define _Included_de_web_computing_HelloWorld_HelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_web_computing_HelloWorld_HelloWorldJNI
 * Method:    messageBox
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_web_1computing_HelloWorld_HelloWorldJNI_messageBox
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
